### PR TITLE
SplitButton border radius

### PR DESCRIPTION
**Pull request by jepsar**
Fixes https://github.com/primefaces/primefaces/issues/11155

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Now you can build the SASS themes and then copy the theme.css over to PF.

**Comment by jepsar** [comment]
> Now you can build the SASS themes and then copy the theme.css over to PF.

Why is this repo not part of primefaces? This was asked before, right?

**Comment by melloware** [comment]
All the sass themes are separate right now and was it a PrimeTek decision.

**Comment by jepsar** [comment]
I'll add a shell script to do the copy of all the css files. I could add it to this repo for reuse.

**Comment by melloware** [comment]
Yes please! and add the note to the README.MD please.

**Pull request merged**
